### ISSUE TITLE
move script tag to bottom of body

### ISSUE THREAD

**Issue by Jbarget** [skibinska/xhr-workshop#3]
the js file will run before the html has loaded which can cause issues with `document.getElementById`

https://github.com/skibinska/xhr-workshop/blob/master/index.html#L6

would be good to move it below line 11

**Comment by skibinska** [comment]
Thanks for raising the issue @Jbarget
I fixed it :)

**Comment by Jbarget** [comment]
fixed with https://github.com/skibinska/xhr-workshop/commit/6b088274cb24d01effe09eebb347dd42d7c46201
